import { Box } from './Box';
import { Circle } from './Circle';
import { Cylinder } from './Cylinder';
import { GeodesicSphere } from './GeodesicSphere';
import { Icosahedron } from './Icosahedron';
import { ParametricCone } from './ParametricCone';
import { Plane } from './Plane';
import { Sphere } from './Sphere';
import { Tetrahedron } from './Tetrahedron';
import { Torus } from './Torus';
import { Triangle } from './Triangle';

export { Box };
export { Circle };
export { Cylinder };
export { GeodesicSphere };
export { Icosahedron };
export { ParametricCone };
export { Plane };
export { Sphere };
export { Tetrahedron };
export { Torus };
export { Triangle };
